### ISSUE TITLE
__KERNEL__ not defined in KDevelop parser

### ISSUE THREAD

**Issue by nathanielhourt** [Gnurou/kdev-kernel#13]
This issue is just what it says on the box. **KERNEL** is not defined, at least for the version of KDevelop and Linux I'm working with.

KDevelop 4.5.1 on KDE 4.10.4
Linux 2.6.26.5 (yes, I know, it's ancient)
Fedora 18
kdev-kernel master branch, cloned July 02 2013

Let me know if there's anything I can do to help.

**Comment by Gnurou** [comment]
Hi, sorry for the late reply. I think you don't see the **KERNEL** symbol defined because you are opening a file that is not in the project. Kdev-kernel tries to guess which source files it needs according to your kernel configuration, and all other files of the kernel are just not handled by it, which also means that extra macros are not defined for them. Could you tell me which file you are trying to open, and maybe attach your .config? The project parser is far from perfect and still has bugs, unfortunately. :/

**Comment by nathanielhourt** [comment]
Ahh, perhaps that's the problem. I was looking in include/linux/tcp.h at
the time, if memory serves, but the issue seems to have resolved itself for
now... Yay for ephemeral bugs. :P

## 

Nathan Hourt

On Mon, Jul 29, 2013 at 2:51 AM, Alexandre Courbot <notifications@github.com

**Comment by Gnurou** [comment]
Great - closing this issue then.
